### ISSUE TITLE
Rebecca: Tangible Artifacts

### ISSUE THREAD

**Issue by rebecca-123** [shreya-ahujaa/SERA#20]
|| Requirements                                                                                                                 |       Runtime                          | Code |
|--|-----------------------------------------------------------------------------------------------------|:------------------------------:|:-:|
|**Frontend UI demo.** |UI takes inputs and passes them to an API and returns data from the backend to frontend. | [Input: sign up](https://shreya-ahujaa.github.io/SERA/signup)<br> [Output from database](https://shreya-ahujaa.github.io/SERA/clubs)| [FE: Signup](https://raw.githubusercontent.com/shreya-ahujaa/SERA/gh-pages/signup.md)|
|**Postman API Demo.** | JSON Raw/Body formatted API passes inputs to backend and updates persistent table. <img width="689" alt="image" src="https://user-images.githubusercontent.com/58576326/218280038-d3805129-d501-4bc1-977a-0595eb1afa3a.png">| [Read: Deployed JSON](https://www.rebeccaaa.tk/api/club/) | [Create: PostMapping with RequestBody](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/mvc/database/club/ClubApiController.java#L80-L86)|
| **Java Demo - Object Creation.** |Tester method that shows creation of Objects and outputs to Terminal, illustrate printing objects (hopefully using toString().<img width="758" alt="image" src="https://user-images.githubusercontent.com/58576326/218280009-40ebbcde-9d53-4ead-a323-9749c6d60f9d.png">| | [Code](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/mvc/database/club/Club.java#L146-L164) |
|**Java Demo - Model Init.** |Delete database and show the creation and population of tables.   Expected in this step is the use of CommandLineRunner and the use of a tool like SQLite Viewer | | [ModelInit.java](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/mvc/ModelInit.java)|
| **Java Demo with Postman or UI** | All CRUD methods.   Above was focused on Create and Read, this is focused on Update and Delete.<img width="676" alt="image" src="https://user-images.githubusercontent.com/58576326/218281318-f39de6fb-9611-4b77-ad47-eed0cf9fa509.png">| | [Update](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/mvc/database/club/ClubApiController.java#L88-L112)<br>[Delete](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/mvc/database/club/ClubApiController.java#L68-L78) |
| **JWT Demo** | Show UI receiving and setting cookie and backend providing cookie through /authenticate like method <img width="959" alt="image" src="https://user-images.githubusercontent.com/58576326/218280362-80733ed7-e6eb-4132-a047-bdfbfc13a63b.png">| | [Backend code providing cookie](https://github.com/Rebecca-123/SERA_spring/blob/main/src/main/java/com/nighthawk/team_backend/mvc/jwt/JwtApiController.java#L73-L79)|

**Comment by MAnn223** [comment]
- [ ] Frontend UI Demo: 0, UI doesn't take input 
- [ ] Postman API Demo: 0.1, Added a club and showed updated table
   - **Not in body** 
- [x] Java Demo Obj Creation: 0.1, used toString method to create a club object
- [x] Java Demo Delete database: 0.1, showed database w mySQLite Viewer 
- [ ] Java Demo w Postman: 0, no update
- [x] JWT Demo: 0.1, howed UI receiving and setting cookie and backend providing cookie through /authenticate like method

0.3
